### ISSUE TITLE
extend `BlobStoreRepository` to support blob metadata

### ISSUE THREAD

**Issue by esuomi** [entur/rutebanken-helpers#301]
As part of Fintraffic's efforts to take NPlan into use we have identified a metadata sharing need from our internal integration requirements which would be covered the easiest by allowing attaching custom metadata to uploaded blobs.

What we want to do is to attach a selected subset of Uttu's [Export entity's](https://github.com/entur/uttu/blob/1010763e9ac69deb7f62db1fd4009cba07c8b8f7/src/main/java/no/entur/uttu/model/job/Export.java) fields, namely at least `name` to the blob itself, and potentially some other contextual information as well which Uttu can provide. The mentioned integration on our side simply monitors new files appearing to S3, so having this ability to attach metadata would allow the integration to pick the relevant contextual metadata from S3 directly. It is worth mentioning that Fintraffic's architecture does not have ESB or any other event messaging platform at the moment, so the blob upload event fired by Uttu cannot be handled anywhere - there's no Marduk equivalent at Fintraffic.

We have our own implementation of [`BlobStoreRepository` for AWS S3](https://github.com/entur/uttu/blob/1010763e9ac69deb7f62db1fd4009cba07c8b8f7/src/main/java/no/entur/uttu/export/blob/S3BlobStoreRepository.java) as part of Uttu, and one challenge to consider here is how the metadata should be passed on to the actual upload command.

While an easy way would be to add yet another overload for `#uploadBlob()`, such as
```java
long uploadBlob(String objectName, InputStream inputStream, Map<String,String> metadata);
```
I'd instead suggest adding a descriptor type for the blob
```java
public record BlobDescriptor(String name, 
                             InputStream inputStream,
                             Optional<String> contentType,
                             Optional<Map<String, String>> metadata) {}
```
and adding an overload with a mandatory-params-only-default for consuming that type instead
```java
default long uploadBlob(BlobDescriptor bd) {
  return uploadBlob(db.name(), bd.inputStream());
}
```

This way existing implementations shouldn't break, and we could do our own extension in Uttu's codebase easily, creating an "add export metadata to blobs" a native feature of Uttu itself.

Some other considerations:

- [GCP also supports custom object metadata](https://cloud.google.com/storage/docs/metadata), which is also form of `Map<String,String>`, so support across implementations could also be implemented.
- The `S3BlobStoreRepository` implementation in Uttu's codebase is currently not coupled to Uttu in any way, so technically speaking it could be moved to `rutebanken-helpers` to make it widely available.
- As more general library, a set of metadata management methods could also be added. We do not have need for these, so this is entirely up to your consideration.

**Comment by vpaturet** [comment]
This sounds good, just make a PR and I'll take a look at it.
