### ISSUE TITLE
migrate AWS S3 blob store implementation from uttu to rutebanken-helpers

### ISSUE THREAD

**Issue by esuomi** [entur/rutebanken-helpers#307]
As part of previous development in uttu we implemented AWS S3 variant of `BlobStoreRepository` (see [uttu/S3BlobStoreRepository](https://github.com/entur/uttu/blob/efbf351a0a913a0d212cb5c1d7921575995acd7a/src/main/java/no/entur/uttu/export/blob/S3BlobStoreRepository.java), [uttu/S3BlobStoreRepositoryConfig](https://github.com/entur/uttu/blob/efbf351a0a913a0d212cb5c1d7921575995acd7a/src/main/java/no/entur/uttu/export/blob/S3BlobStoreRepositoryConfig.java), [uttu/S3BlobStoreRepositoryTest](https://github.com/entur/uttu/blob/efbf351a0a913a0d212cb5c1d7921575995acd7a/src/test/java/no/entur/uttu/export/blob/S3BlobStoreRepositoryTest.java)) and as we have now identified the need to use this potentially also in tiamat, I'm up to doing the legwork of moving the relevant code and tests to `rutebanken-helpers` by creating a new module out of it.

However, there are a few other related things I'd like to get done as well:

### 1. Rename current module directories so that they categorize better

The current modules are named a bit this-and-that, and while they read naturally, they don't organise quite well. What I mean by this is that the storage modules currently are
```shell
gcp-storage
storage
```
and adding AWS S3 would be `s3-storage` with the same pattern, which IMHO isn't very good way to create submodules as they are not alphabetical and natural string ordering doesn't group them properly. So, I'd suggest renaming the modules with three level notation, either `vendor-product-kind` or `kind-vendor-product` yielding names such as the ones below:
```shell
# vendor-product-kind:
aws-s3-storage
gcp-gcs-storage
entur-storage # or just storage
rutebanken-storage-starter # or entur-storage-starter or just storage-starter

# kind-vendor-product:
storage
storage-spring-starter
storage-aws-s3
storage-gcp-gcs
```

The latter form IMHO simply looks better, and also extends more easily - AWS for example has multiple potential storages available, such as [Glacier](https://aws.amazon.com/s3/storage-classes/glacier/), I believe GCP also has other alternatives, and Azure has like dozen different things in various stages of deprecation that could potentially be supported.

Additionally I don't mind keeping the actual published artefact names the way they are - no need to break backwards compatability just for the sake of it :)

### 2. Create a Spring Boot Starter for all storages to make it easier to take any implementation in use in any service

With all these implementations comes need for configuration, and as I've had a look at uttu and tiamat now, I've noticed that the configurations are somewhat different. This is why I believe a custom Spring Boot Starter for storages would be a great addition, built in such a way that by default it starts only in-memory variants, and only by adding the correct submodule as dependency **and** its relevant configuration it would do automatic configuration and initialization.

So, I'd be very interested to hear from @vpaturet et al if all this sounds reasonable, as I could start working on these quite soon.

**Comment by vpaturet** [comment]
The naming convention:
```
storage
storage-aws-s3
storage-gcp-gcs
```
sounds good.
That will break existing components but this is a small Maven configuration change. We just need to bump the major version.
I am less convinced by the Spring Boot starter, I feel that it often gets in the way.
I guess we can start without a starter in a first release and reconsider it in a subsequent release.
