### ISSUE TITLE
Cannot compile due to non-existing com.google.cloud:pubsub-emulator package

### ISSUE THREAD

**Issue by lazee** [entur/rutebanken-helpers#71]
Getting this message upon build:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:copy (copy-pubsub-emulator) on project entur-google-pubsub: Unable to find/resolve artifact.: Could not find artifact com.google.cloud:pubsub-emulator:jar:0.1-SNAPSHOT -> [Help 1]
```

I guess you have it proxied somewhere, and that it is not part of the public Maven repositories anymore?

**Comment by vpaturet** [comment]
Thank you for reporting this issue.
Some modules depend on Google PubSub Emulator for running unit tests.
The emulator is not available as a Maven dependency in any public Maven repository, thus additional configuration is required for building the project.
The README file has been updated to describe this.
